columbia:
  job-check-interval: PT1H

logging:
  level:
    ROOT: WARN
    it.mulders: INFO

spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog.xml
  main:
    banner-mode: off
  mustache:
    check-template-location: false

vaadin:
  whitelisted-packages=it/mulders/columbia/