columbia:
  aws:
    access-key-id: access-key-id
    region: eu-central-1
    secret-access-key: secret-access-key
  job-check-interval: PT1M

logging:
  level:
    ROOT: WARN
    it.mulders: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/columbia
    username: columbia
    password: columbia
  devtools:
    restart:
      enabled: true
      poll-interval: 2s
      quiet-period: 1s