#!/bin/sh

group=columbia
if ! getent group | grep -q "^$group:" ;
then
    echo "Creating system group: $group"
    groupadd -r $group
fi

user=columbia
descr="Columbia system user"
shell=/bin/false
if ! getent passwd | grep -q "^$user:";
then
    echo "Creating system user: $user in $group with $descr and shell $shell"
    useradd --gid $group -r --shell $shell -c "$descr" $user -d /opt/columbia
fi