name: CI build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up cache for ~./m2/repository
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: columbia-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            columbia-

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 15

      - name: Build
        run: mvn verify -e -B -V -Dsha1=$(git rev-parse HEAD | cut -c1-8)

      - name: Upload application
        uses: actions/upload-artifact@v2
        if: github.ref == 'refs/heads/master'
        with:
          name: columbia.jar
          path: target/columbia.jar
