name: Mutation testing

on:
  push:
    branches:
      - master
  schedule:
    - cron: '14 3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up cache for ~./m2/repository
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: columbia-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            columbia-

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 15

      - name: Run mutation testing
        run: mvn verify -e -B -V -Dsha1=$(git rev-parse HEAD | cut -c1-8) -P mutation-testing
