name: Mutation testing

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache ~/.m2/repository
        uses: actions/cache@v2.1.4
        with:
          path: ~/.m2/repository
          key: columbia-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            columbia-

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 15

      - name: Run mutation testing
        run: mvn test -e -B -V -Dsha1=$(git rev-parse HEAD | cut -c1-8) -P mutation-testing

      - name: Upload mutation test report
        run: ./.github/upload-mutation-report.sh
        env:
          API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}